### ISSUE TITLE
Zero Health does not work at all in 0.3.3 also no CHAR_SubZero_F option in the menu

### ISSUE THREAD

**Issue by Swordsmagus** [ermaccer/MK9Hook#2]
The title say it all but CHAR_SubZero_F is basically MK3 Subzero costume that can't be access in the character menu thing even though it works in the script file thing, (I know my english very well /s)

![image](https://user-images.githubusercontent.com/107529267/192706578-30934ae1-091f-4ff0-af93-94767b2f451d.png)

**Comment by ermaccer** [comment]
fixed & added
